# Rosetta Stone CocoaDocs template

highlight-font: '"GT Walsheim", "gt_walsheim_regular", "Avant Garde Gothic ITCW01Dm", "Avant Garde", "Helvetica Neue", "Arial'
body: '"Helvetica Neue", "Arial", san-serif'
code: '"Monaco", "Menlo", "Consolas", "Courier New", monospace'

highlight-color: "#4195D3"
highlight-dark-color: "#3272A1"
darker-color: "#4195D3"
darker-dark-color: "#224E6E"
background-color: "#f9db35"
alt-link-color: "#706F72"
warning-color: "#FAEB96"
